# Generated by Django 6.0.6 on 2026-06-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passes', '0007_alter_passinstance_customer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ticket_types', models.JSONField(default=list, help_text="JSON array of ticket types: [{'name': 'VIP', 'price': 50.00, 'qty': 100}, ...]", verbose_name='Ticket Types')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='passes.company')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=100, unique=True, verbose_name='Order Reference')),
                ('ticket_type', models.CharField(max_length=100, verbose_name='Ticket Type')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Buyer Name')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Buyer Email')),
                ('pdf_url', models.CharField(blank=True, max_length=500, verbose_name='PDF Ticket URL')),
                ('is_scanned', models.BooleanField(default=False, verbose_name='Is Scanned')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Scanned At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ticketing.event')),
                ('pass_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_order', to='passes.passinstance')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL)),
                ('stripe_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='passes.stripetransaction')),
            ],
            options={
                'verbose_name': 'Ticket Order',
                'verbose_name_plural': 'Ticket Orders',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('total_capacity', models.PositiveIntegerField(default=100, verbose_name='Total Capacity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='passes.company')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('company', 'slug')},
        ),
    ]
