"""
Django settings for wallet_platform project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['*']),
)
# Read local .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-jz)8*!e^8yg04t$m5z-jc7io_gmr-#$f!n)o&^h#)2v=1(jw$4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
# Always allow the custom domain in production, plus vertical domains and localhost subdomains
extra_hosts = [
    'unisonpass.com', 'www.unisonpass.com',
    'tickets.com', 'www.tickets.com',
    'gym.com', 'www.gym.com',
    'cafe.com', 'www.cafe.com',
    '.localhost', 'localhost', '127.0.0.1'
]
for host in extra_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

VERTICAL_DOMAINS = {
    'tickets.com': 'TICKETING',
    'www.tickets.com': 'TICKETING',
    'gym.com': 'GYM',
    'www.gym.com': 'GYM',
    'cafe.com': 'CAFE',
    'www.cafe.com': 'CAFE',
    # local development domains
    'tickets.localhost': 'TICKETING',
    'gym.localhost': 'GYM',
    'cafe.localhost': 'CAFE',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    
    # Custom apps
    'passes.apps.PassesConfig',
    'ticketing.apps.TicketingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'wallet_platform.middleware.SiteDetectionMiddleware',  # Multi-vertical detection middleware
    'django.middleware.locale.LocaleMiddleware',  # Added for multi-language support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wallet_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wallet_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Translation configuration (Future-proofed for multiple languages)
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configure WhiteNoise for static files serving in production
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================================================================
# WALLET CREDENTIALS (APPLE & GOOGLE)
# ======================================================================
GCP_PROJECT_ID = env('GCP_PROJECT_ID', default='wallet-devcertifit')
GCP_LOCATION = env('GCP_LOCATION', default='europe-west3')
GCP_TASKS_QUEUE_NAME = env('GCP_TASKS_QUEUE_NAME', default='ticketing-fulfillment')
APP_DOMAIN = env('APP_DOMAIN', default='')

APPLE_TEAM_IDENTIFIER = env('APPLE_TEAM_IDENTIFIER', default='12345ABCDE')
APPLE_PASS_CERT = env('APPLE_PASS_CERT', default='')
APPLE_PASS_KEY = env('APPLE_PASS_KEY', default='')
APPLE_WWDR_CERT = env('APPLE_WWDR_CERT', default='')

GOOGLE_WALLET_ISSUER_ID = env('GOOGLE_WALLET_ISSUER_ID', default='3388000000023141985')
GOOGLE_SERVICE_ACCOUNT_EMAIL = env('GOOGLE_SERVICE_ACCOUNT_EMAIL', default='')

# Load and correctly format the JSON key (newlines are escaped in Secret Manager)
_google_key = env('GOOGLE_SERVICE_ACCOUNT_KEY', default='')
GOOGLE_SERVICE_ACCOUNT_KEY = _google_key.replace('\\n', '\n') if _google_key else None

# ======================================================================
# STRIPE CREDENTIALS & VERTICAL FEES
# ======================================================================
from decimal import Decimal
STRIPE_PUBLIC_KEY = env('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
TICKETING_FEE_FIXED = Decimal(env('TICKETING_FEE_FIXED', default='0.50'))

# Security settings for HTTPS proxy (Cloud Run)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'https://wallet-app-ioidrsi2kq-lz.a.run.app',
    'https://wallet-app-192038178935.europe-north1.run.app',
]
if APP_DOMAIN:
    domain_clean = APP_DOMAIN.replace('https://', '').replace('http://', '')
    CSRF_TRUSTED_ORIGINS.append(f'https://{domain_clean}')



