# Generated by Django 6.0.6 on 2026-06-09 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='PassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Serial Number (Apple)')),
                ('google_object_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google Object ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance (Points/Currency)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pass Instance',
                'verbose_name_plural': 'Pass Instances',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='passes.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='PassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATE', 'Created'), ('INSTALL', 'Installed'), ('UNINSTALL', 'Uninstalled'), ('UPDATE', 'Updated'), ('REDEMPTION', 'Redeemed')], max_length=20, verbose_name='Event Type')),
                ('value_changed', models.DecimalField(decimal_places=2, default=0.0, help_text='Difference in points or currency balance', max_digits=10, verbose_name='Value Changed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='passes.company')),
                ('pass_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='passes.passinstance')),
            ],
            options={
                'verbose_name': 'Pass Analytics',
                'verbose_name_plural': 'Pass Analytics Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('LOYALTY', 'Loyalty Card'), ('GIFT_CARD', 'Gift Card'), ('MEMBERSHIP', 'Membership Card')], max_length=20, verbose_name='Pass Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pass_logos/', verbose_name='Logo Image')),
                ('background_color', models.CharField(default='#4f46e5', max_length=7, verbose_name='Background Color (Hex)')),
                ('foreground_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Foreground Color (Hex)')),
                ('label_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Label Color (Hex)')),
                ('apple_pass_type_id', models.CharField(blank=True, max_length=100, verbose_name='Apple Pass Type ID')),
                ('google_class_id', models.CharField(blank=True, max_length=255, verbose_name='Google Wallet Class ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='passes.company')),
            ],
            options={
                'verbose_name': 'Pass Template',
                'verbose_name_plural': 'Pass Templates',
            },
        ),
        migrations.AddField(
            model_name='passinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='passes.passtemplate'),
        ),
    ]
