# Generated by Django 6.0.6 on 2026-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtemplate',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional custom developer JSON metadata.', verbose_name='Custom Metadata'),
        ),
        migrations.AddField(
            model_name='passtemplate',
            name='sku',
            field=models.CharField(blank=True, help_text='Optional product/service SKU code.', max_length=100, null=True, verbose_name='SKU Code'),
        ),
    ]
