# Generated by Django 6.0.6 on 2026-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_passtemplate_custom_metadata_passtemplate_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtemplate',
            name='pass_type',
            field=models.CharField(choices=[('LOYALTY', 'Loyalty Card'), ('GIFT_CARD', 'Gift Card'), ('MEMBERSHIP', 'Membership Card'), ('COUPON', 'Coupon / Offer'), ('EVENT_TICKET', 'Event Ticket'), ('BOARDING_PASS', 'Boarding Pass'), ('GENERIC', 'Generic Pass')], max_length=20, verbose_name='Pass Type'),
        ),
    ]
