# Generated by Django 6.0.6 on 2026-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_passtemplate_pass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='passinstance',
            name='pass_data',
            field=models.JSONField(blank=True, default=dict, help_text='Specific details for this pass instance (e.g. seat, flight, tier, expiry).', verbose_name='Pass Instance Data'),
        ),
        migrations.AddField(
            model_name='passtemplate',
            name='default_data',
            field=models.JSONField(blank=True, default=dict, help_text='Default key-value dictionary for this card design.', verbose_name='Default Template Data'),
        ),
    ]
