# Generated by Django 6.0.6 on 2026-06-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_passinstance_pass_data_passtemplate_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Custom Domain'),
        ),
        migrations.AddField(
            model_name='company',
            name='vertical',
            field=models.CharField(choices=[('TICKETING', 'Ticketing'), ('GYM', 'Gym'), ('CAFE', 'Cafe'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20, verbose_name='Vertical'),
        ),
        migrations.AddField(
            model_name='passinstance',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='passinstance',
            name='vertical',
            field=models.CharField(choices=[('TICKETING', 'Ticketing'), ('GYM', 'Gym'), ('CAFE', 'Cafe'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20, verbose_name='Vertical'),
        ),
        migrations.AlterField(
            model_name='passanalytics',
            name='event_type',
            field=models.CharField(choices=[('CREATE', 'Created'), ('INSTALL', 'Installed'), ('UNINSTALL', 'Uninstalled'), ('UPDATE', 'Updated'), ('REDEMPTION', 'Redeemed'), ('CHECK_IN', 'Checked In'), ('PURCHASE', 'Purchased'), ('CLASS_BOOKED', 'Class Booked'), ('TICKET_SCANNED', 'Ticket Scanned'), ('STRIPE_CHARGE', 'Stripe Charge')], max_length=20, verbose_name='Event Type'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='passes.company')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='passinstance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_instances', to='passes.location'),
        ),
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(choices=[('TICKETING', 'Ticketing'), ('GYM', 'Gym'), ('CAFE', 'Cafe')], max_length=20, verbose_name='Vertical')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Amount')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Platform Fee')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_transactions', to='passes.company')),
            ],
            options={
                'verbose_name': 'Stripe Transaction',
                'verbose_name_plural': 'Stripe Transactions',
            },
        ),
    ]
