# Generated by Django 6.0.6 on 2026-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_company_custom_domain_company_vertical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vertical',
            field=models.CharField(choices=[('TICKETING', 'Ticketing'), ('GYM', 'Gym'), ('CAFE', 'Cafe')], default='TICKETING', max_length=20, verbose_name='Vertical'),
        ),
        migrations.AlterField(
            model_name='passinstance',
            name='vertical',
            field=models.CharField(choices=[('TICKETING', 'Ticketing'), ('GYM', 'Gym'), ('CAFE', 'Cafe')], default='TICKETING', max_length=20, verbose_name='Vertical'),
        ),
    ]
