# Generated by Django 6.0.6 on 2026-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_alter_company_vertical_alter_passinstance_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passinstance',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='passinstance',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer Name'),
        ),
    ]
