# Generated by Django 6.0.6 on 2026-06-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0007_alter_passinstance_customer_email_and_more'),
        ('ticketing', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='ticket_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_transactions', to='ticketing.ticketorder'),
        ),
    ]
